const IDENTIFIER_USER = '192a5b3feb03da51d09ded8e';

const pageElements = {
    form : '.popup__container',
    inputForm: '.popup__field',
    buttonSaveForm: '.popup__save_button',
    popupEditProfile : '#popupEditProfile',
    popupAddCard: '#popupAddCard',
    popupViewPhoto: '#popupViewPhoto',
    popupEditAvatar: '#popupEditAvatar',
    popupDeleteCard: '#popupDeleteCard',
    spanForm : '.popup__field-error',
    formEditProfile: '.popup__container_edit-profile',
    formCardAdd: '.popup__container_add-card',
    formEditAvatar: '.popup__container_edit-avatar-form',
    sectionElements: '.elements',
    inputNamePopupEditProfile: '.popup__field_name_person',
    inputInfoPopupEditProfile: '.popup__field_inform_person',
    buttonOpenPopupAddCard: '.profile__add-button',
    buttonOpenPopupEditAvatar: '.profile__avatar-opacity',
    buttonClosePopup: '.popup__icon-close',
    buttonOpenPopupEditProfileInfo: '.profile-info__edit-button',
    buttonSavePopupEditProfile : '#buttonSavePopupEditProfile',
    buttonSavePopupAddCard : '#buttonSavePopupAddCard',
    buttonSavePopupEditAvatar : '#buttonSavePopupEditAvatar',
    buttonDeleteCardInPopup: '.popup__button_delete-card',
    namePage: '.profile-info__name',
    informPage: '.profile-info__information-person',
    containerPopupViewPhoto: '.popup__view-photo-container',
    infoPopupViewPhoto: '.popup__view-photo-info',
    templateCard: '#card',
    mainContainerPopupViewPhoto: '.popup__main-container',
    modifyClassFormInputTypeError : 'form__input_type_error',
    modifyClassPopupFieldError: 'popup__field-error_active',
    modifyClassButtonSaveBlocking : 'popup__save_button_blocking',
    modifyClassButtonDeleteCardDeactivation: 'element__button-delete_deactivation',
    countLike : '.element__count-like',
    avatar: '.profile__avatar'
  }

  export  { pageElements, IDENTIFIER_USER};